### ISSUE TITLE
patterns.sociocracy30.org is inaccessible

### ISSUE THREAD

**Issue by ligaz** [S3-working-group/s3-practical-guide#20]
Hey there,

It looks like http://patterns.sociocracy30.org is inaccessible and results in 404 from GitHub pages.

**Comment by bboc** [comment]
Thanks, I'm already aware of this, it appears that this is likely caused by a problem with Github, because after the latest code change (yesterday) I checked that everything is ok. I'm trying to figure out where to report this.

**Comment by ligaz** [comment]
It looks like it has been fixed. Thanks.

Not sure what the problem was, but I would be glad to help with anything in order to prevent this in the future.

**Comment by bboc** [comment]
No, it's not fixed, it's even more messed up. The problem is with most likely with github, because the problem appeared right  after I renamed the master branch to release. The GUI shows a problem with building the CSS from SASS, but I haven't changed any code, since I last verified that the page was up, and the CSS builds just fine locally. 

Now that I renamed the branch back to master, there is still another branch called released, and even though the github GUI claims the site is building from master, it is in fact building from release. I don't think there is much I can do here, apart from filing a bug with github. Except it looks like they have no place for filing bugs. Any ideas?

**Comment by ligaz** [comment]
Indeed it's not. I clicked on a couple of pages but it looks I somehow got lucky.

I'm not seeing the `master` branch pushed to GitHub. Is there a possibility that you have renamed it locally and have not pushed it yet?

**Comment by bboc** [comment]
I have renamed it through the github website, and then updated my local branches.

**Comment by ligaz** [comment]
I've just checked it and it looks OK. The default branch is the `develop` one and your [latest push](https://github.com/S3-working-group/s3-practical-guide/commit/e0fbedc71f26e9d423f0206d6bc44b078232c9e1) seems to have resolved it.
